version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "serverlocal"
    network_mode: "host"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
    - "8000:8000"
    volumes:
    - ${PWD}/config/:/app/config/
    restart: on-failure