openapi: "3.0.2"
info:
  title: Go API Template
  version: "1.0.0"
servers:
  - url: "http://localhost:8000/api/v1"

security:
  - bearerAuth: []

paths:
  /user/register:
    post:
      operationId: "registerUser"
      tags:
        - "User"
      description: "Register User"
      security: []
      requestBody:
        required: true
        description: "Registration Request"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/activate:
    post:
      operationId: "activateUser"
      tags:
        - "User"
      description: "Activate User"
      security: []
      parameters:
        - in: query
          name: token
          schema:
            type: string
          description: The activation token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/login:
    post:
      operationId: "loginUser"
      tags:
        - "User"
      description: "Login User"
      security: []
      requestBody:
        required: true
        description: "Login Request"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLoginResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /user/profile:
    get:
      operationId: "userProfile"
      tags:
        - "User"
      description: "User Profile"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      operationId: "updateUserProfile"
      tags:
        - "User"
      description: "User Profile Update"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: "User Profile Update Request"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileUpdateRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    UserRegistrationRequest:
      type: object
      required:
        - email
        - first_name
        - last_name
        - password
        - mobile
        - address
      properties:
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
        mobile:
          type: string
        address:
          type: string

    UserLoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserLoginResponse:
      type: object
      required:
        - token
        - first_name
        - last_name
      properties:
        token:
          type: string
        first_name:
          type: string
        last_name:
          type: string

    UserProfile:
      type: object
      required:
        - email
        - first_name
        - last_name
        - mobile
        - address
        - image_url
      properties:
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        mobile:
          type: string
        address:
          type: string
        image_url:
          type: string

    UserProfileUpdateRequest:
      type: object
      properties:
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        mobile:
          type: string
        address:
          type: string
        image_url:
          type: string

    Status:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    Error:
      type: object
      required:
        - message
        - error
      properties:
        error:
          type: string
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
